In [ ]:
Python 3.11.x ('venv')

In [4]:
import pandas as pd
data = pd.read_csv("../data/aiml_training_data.csv")
data.head()

                           text        intent  confidence
0            Where is my order?  order_status        0.77
1  When will my package arrive?  order_status        0.91
2         Track my order please  order_status        0.75
3  Order tracking update needed  order_status        0.83
4     Has my order shipped yet?  order_status        0.90

In [6]:
data.columns.tolist()
data.shape
data.isnull().sum()

text          0
intent        0
confidence    0
dtype: int64

In [7]:
data.head(10)

                            text          intent  confidence
0             Where is my order?    order_status        0.77
1   When will my package arrive?    order_status        0.91
2          Track my order please    order_status        0.75
3   Order tracking update needed    order_status        0.83
4      Has my order shipped yet?    order_status        0.90
5  I want to return this product  return_request        0.82
6    How do I initiate a return?  return_request        0.94
7  Return policy for electronics  return_request        0.79
8     Can I return after 7 days?  return_request        0.95
9       Return pickup scheduling  return_request        0.81

In [8]:
data.shape

(230, 3)

In [9]:
data.columns.tolist()

['text', 'intent', 'confidence']

In [1]:
import pandas as pd
import sys

print("Python version:", sys.version)

Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

In [2]:
from pathlib import Path

project_root = Path.cwd().parent
data_path = project_root / "data" / "aiml_training_data.csv"

df = pd.read_csv(data_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (230, 3)

In [3]:
df.head(10)

                            text          intent  confidence
0             Where is my order?    order_status        0.77
1   When will my package arrive?    order_status        0.91
2          Track my order please    order_status        0.75
3   Order tracking update needed    order_status        0.83
4      Has my order shipped yet?    order_status        0.90
5  I want to return this product  return_request        0.82
6    How do I initiate a return?  return_request        0.94
7  Return policy for electronics  return_request        0.79
8     Can I return after 7 days?  return_request        0.95
9       Return pickup scheduling  return_request        0.81

In [5]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
text          0
intent        0
confidence    0
dtype: int64

In [4]:
print("Columns:")
print(df.columns.tolist())

Columns:
['text', 'intent', 'confidence']